Initial commit
hazelops/terraform-aws-budget-alert pull request #1
Opened 2021-02-24 09:13 UTC by kobrikx

#### What's new:

 - Create module
 - Create Readme.md

2021-02-24 09:53 UTC, DimmKirr requested changes
Minor comment

2021-02-24 09:53 UTC, DimmKirr commented on main.tf
> +  count                  = var.enabled ? 1 : 0
minor: indent is a bit off

2021-03-05 14:12 UTC, kobrikx commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create monitoring alert for AWS Budget anomaly detector](https://trello.com/c/8TYmmT9w/180-create-monitoring-alert-for-aws-budget-anomaly-detector)

2021-03-11 13:36 UTC, DimmKirr requested changes
Looks good overall. But I'd add more links to the official aws documentation.

2021-03-11 13:36 UTC, DimmKirr commented on variables.tf
> +variable "aws_account_id" {
Do we need to use a variable or we should rather use data?

2021-03-11 13:36 UTC, DimmKirr commented on variables.tf
> +  description = "Budget service cost filter, eg: Amazon Elastic Compute Cloud - Compute / Amazon Relational Database Service / Amazon Redshift / Amazon ElastiCache/ Amazon Elasticsearch Service"
Please add a comment with a link to documentation for this parameter (to aws website, possibly?)

2021-03-11 15:24 UTC, kobrikx commented on variables.tf
> +  description = "Budget service cost filter, eg: Amazon Elastic Compute Cloud - Compute / Amazon Relational Database Service / Amazon Redshift / Amazon ElastiCache/ Amazon Elasticsearch Service"
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-what-is.html

2021-03-11 17:15 UTC, DimmKirr approved these changes
Looks good, besides typo in README.

2021-03-11 17:15 UTC, DimmKirr commented on README.md
> +  time_period_start = "2021-01-01_00:00"
No closing bracket here

2021-03-11 18:18 UTC, merged